name: Development Pipeline
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  checkout:
    name: Clone the repo
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.output.outputs.tag }}
    steps:
      - name: Install dependencies
        run: go mod download

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Extract Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/cagdaskarademir/${{ github.event.repository.name }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=development
            type=sha

      # Login the Github
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_SECRET_KEY }}

      # Build and Push Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Write version of output
        id: output
        run: |
          echo "tag=sha-$(echo $GITHUB_SHA | cut -c1-7)" >> "$GITHUB_OUTPUT"
